# Generated by Django 5.2.9 on 2025-12-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eegfile_status_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('doctor', 'Médico'), ('auditor', 'Auditor')], default='doctor', max_length=20),
        ),
    ]
