# Generated by Django 5.2.9 on 2025-12-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador do Sistema'), ('doctor', 'Médico'), ('auditor', 'Auditor')], default='doctor', max_length=20),
        ),
    ]
